#!/bin/bash
# MySQL 密码重置脚本

echo "=========================================="
echo "MySQL 密码重置脚本"
echo "=========================================="
echo ""
echo "选项1：停止MySQL，以跳过权限检查模式启动，然后重置密码"
echo "选项2：使用已知密码连接"
echo ""
echo "您是否记得MySQL的root密码？(y/n)"
echo ""
echo "如果不记得，我将帮您重置密码为: cco123456"
echo ""
echo "请运行以下命令重置密码："
echo ""
echo "# 1. 停止MySQL服务"
echo "brew services stop mysql"
echo ""
echo "# 2. 以跳过权限检查模式启动MySQL（在新终端窗口运行）"
echo "mysqld_safe --skip-grant-tables &"
echo ""
echo "# 3. 在另一个终端连接MySQL并重置密码"
echo "mysql -u root"
echo "FLUSH PRIVILEGES;"
echo "ALTER USER 'root'@'localhost' IDENTIFIED BY 'cco123456';"
echo "exit"
echo ""
echo "# 4. 停止跳过权限检查的MySQL进程"
echo "killall mysqld"
echo ""
echo "# 5. 正常启动MySQL"
echo "brew services start mysql"
echo ""
echo "# 6. 测试新密码"
echo "mysql -u root -pcco123456 -e \"SELECT 1;\""
echo ""
echo "=========================================="

